@startuml
class HTTPEntity  {
  <implements Requests>
  -- public --
  HTTPResponse get(string url, dict pathParams, dict headers)
  HTTPResponse delete(string url, dict pathParams, dict headers)
  HTTPResponse post(string url, dict body, dict headers)
  HTTPResponse update(string url, dict body, dict headers)
}
@enduml

