@startuml
class IUDXEntity  {
  Catalogue catalogue
  -- private variables --
  ResourceServer _rs
  list<dict> _resources
  Dict _resourceGroups

  -- public methods --
  list<dict> get_resources()
  Dict get_resourceGroups()
  Entities get_entites(CatalogueQuery query)
  Entity get_entity(str entity_id)
}


class Entities {
    <extends iterable>
    List<Entity> _entities
}


class Entity {
    -- public variables --
    ResourceServer rs
    list<str> resources
    -- private variables --
    string _iudx_entity_type
    string _voc_url
    dict _cat_doc
    dict _data_descriptor
    list<dict> _geo_properties
    list<dict> _time_properties
    list<dict> _quantitative_properties
    list<dict> _properties
    -- public methods --
    Entity set_rs(str rs_url, optional str token, option dict headers)
    pandas.DataFrame latest()
    pandas.DataFrame during_search(str start_time, str end_time)
    pandas.DataFrame property_search(str key, str/float value, str operation)
    pandas.DataFrame geo_search(str geoproperty,
        \t str geometry, str georel, 
        \t int _max_distance, list coordinates)
}
@enduml
