@startuml
class ResourceServer  {
    <extends HttpEntity>
  -- public variables --
  Enum IUDXEntityEnum
  str url (default to staticurl)
  optional str token (required for onboarders)
  optional list headers
  -- public methods --
  Resource init(str rs_url, optional str token, option dict headers)
  bool status() // check status
  ResourceResult getData(ResourceQuery query) // 
}

class HTTPEntity  {
  <extends Requests>
  -- public variables --
  dict cert // (str cert, str key)
  -- public methods --
  HTTPResponse get(str url, dict headers)
  HTTPResponse delete(str url, dict headers)
  HTTPResponse post(str url, dict body, dict headers)
  HTTPResponse update(str url, dict body, dict headers)
}

class HTTPResponse {
  <extends requests.Response>
  -- private variables --
  Response _response
  -- public methods --
  dict json()
  int status_code()

}


class ResourceQuery {
    -- private variables--
    str _geoproperty, _geometry, _georel
    int _max_distance
    list _coordinates
    str key
    <str/float> value
    list<str> _filters
    list<str> entities
    -- public methods --
    ResourceQuery add_entity(String id) // add an id to entities
    ResourceQuery geo_search(str geoproperty,
        \t str geometry, str georel, 
        \t int _max_distance, list coordinates)
    ResourceQuery during(str start_time, str end_time)
    ResourceQuery property(str key,
        \t str/float value)
    ResourceQuery add_filters(list<str> filters)
    str get_query()
}


class ResourceResult {
    -- public variables --
    list<dict> results
    int total_hits
    -- public --
}



@enduml
